services:
  postgres:
    container_name: postgres-sql-wac
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: whatsapp_clone
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - whatsapp-clone
    restart: unless-stopped
  keycloak:
    container_name: keycloak-wac
    image: quay.io/keycloak/keycloak:26.0.0
    ports:
      - 9090:8080
    environment:
      # Conexão com o Banco de Dados
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: whatsapp_clone
      KC_DB_USERNAME: username
      KC_DB_PASSWORD: password
      # Configuração do Admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      # Configuração de Hostname para CORS
      KC_HOSTNAME: localhost
    networks:
      - whatsapp-clone
    command:
      - "start-dev"
    depends_on:
      - postgres

networks:
  whatsapp-clone:
    driver: bridge

volumes:
  postgres:
    driver: local
